image: python:3
lint:
 stage: test
 script:
 - pip install yapf==0.32.0
 - yapf --recursive . --style google
 only:
 - pushes

unittest:
  stage: test
  script:
  - pip install requirements.txt
  - pytest
  only:
  - pushes